-- ============================================================================
-- FK Home — r0.22 (Ship 2a): universal task model
-- ============================================================================
-- Extends the existing `tasks` table (r0.10 lifecycle) into the one model that
-- holds ALL work-shapes for every department — without changing how the review
-- / onboarding / probation lifecycle already works.
--
-- PRINCIPLE (learned the hard way): do NOT rewrite working code to fit a new
-- shape — extend the shape so working code keeps working. Every existing column
-- is preserved; the review lifecycle (generate → pending → open → due → overdue
-- → done, reviewer + orchestrator routing, the 06:00 cron) is untouched.
--
-- This migration is ADDITIVE + idempotent:
--   1. Add the universal columns (source, parent_task_id, department_id,
--      category, moved_at, movement_note, meta).
--   2. Widen the kind CHECK (was 'review' only) to all work-shapes.
--   3. Relax NOT NULLs that are review-specific (related_user_id, reason,
--      opens_at, due_at) so ad-hoc / event / recruitment tasks are valid.
--   4. Wipe dummy task rows (staging only — confirmed no real tasks exist).
-- ============================================================================

-- ---------- 1. New universal columns ----------
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS source         TEXT;          -- auto_event | recurring | manual | cron
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS parent_task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS department_id  INTEGER REFERENCES departments(id);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS category       TEXT;          -- free label within a kind (e.g. ad_hoc → 'recruitment')
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS moved_at       TIMESTAMPTZ;   -- multi-day work: when it last moved
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS movement_note  TEXT;          -- "what moved today" (feeds daily report later)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS meta           JSONB;         -- per-type fields (candidate salary/notice/CV-ref, campaign_id, etc.)

CREATE INDEX IF NOT EXISTS idx_tasks_parent ON tasks(parent_task_id) WHERE parent_task_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_kind_status ON tasks(kind, status) WHERE status NOT IN ('done','cancelled');
CREATE INDEX IF NOT EXISTS idx_tasks_dept ON tasks(department_id) WHERE department_id IS NOT NULL;

-- ---------- 2. Widen the kind CHECK ----------
-- Was CHECK (kind IN ('review')). Add the new work-shapes + onboarding/probation.
DO $$
DECLARE c TEXT;
BEGIN
  SELECT conname INTO c FROM pg_constraint
   WHERE conrelid = 'tasks'::regclass AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%kind%';
  IF c IS NOT NULL THEN EXECUTE format('ALTER TABLE tasks DROP CONSTRAINT %I', c); END IF;

  ALTER TABLE tasks ADD CONSTRAINT tasks_kind_chk CHECK (kind IN (
    'review',         -- existing lifecycle review reminder
    'onboarding',     -- onboarding checklist item (future first-class)
    'probation',      -- probation decision
    'event',          -- auto-generated from an FK Home event (leave/lateness/etc)
    'recurring',      -- rota / routine task
    'ad_hoc',         -- manually added unplanned work
    'recruitment'     -- opening (parent) or candidate (child)
  ));
END $$;

-- ---------- 3. Widen the reason CHECK + relax review-specific NOT NULLs ----------
DO $$
DECLARE c TEXT;
BEGIN
  SELECT conname INTO c FROM pg_constraint
   WHERE conrelid = 'tasks'::regclass AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%reason%';
  IF c IS NOT NULL THEN EXECUTE format('ALTER TABLE tasks DROP CONSTRAINT %I', c); END IF;
END $$;
-- reason now free-form + nullable (review uses 'reviewer'/'orchestrator'; other kinds leave it null)
ALTER TABLE tasks ALTER COLUMN reason DROP NOT NULL;

-- related_user_id: nullable — a recruitment opening / generic ad-hoc has no related person
ALTER TABLE tasks ALTER COLUMN related_user_id DROP NOT NULL;

-- opens_at / due_at: nullable — ad-hoc / "what I did today" tasks have no schedule
ALTER TABLE tasks ALTER COLUMN opens_at DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN due_at   DROP NOT NULL;

-- ---------- 4. Tag existing rows + wipe dummy data ----------
-- Any pre-existing review tasks were generated by the lifecycle cron → source='cron'.
UPDATE tasks SET source = 'cron' WHERE source IS NULL AND kind = 'review';

-- STAGING ONLY: wipe dummy/test task rows (confirmed: no real tasks in use yet).
-- This clears the slate for the real task system. Review RECORDS live in
-- profile_notes and are NOT touched — only the tasks queue is cleared.
DELETE FROM tasks;
